Sure, here's the Gemfile with repeated gems removed:

```ruby
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.3'
gem 'puma', '~> 3.12'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'turbolinks', '~> 5'
gem 'webpacker', '~> 4.x'
gem 'font-awesome-rails', '~>4.x'
gem 'jbuilder', '~> 2.5'
gem 'rake', '~> 12.3'
gem 'concurrent-ruby', '~> 1.1'
gem 'i18n', '~> 1.6'
gem 'minitest', '~> 5.12'
gem 'thread_safe', '~> 0.3'
gem 'tzinfo', '~> 1.2'
gem 'activesupport', '~> 5.2'
gem 'builder', '~> 3.2'
gem 'erubi', '~> 1.9'
gem 'mini_portile2', '~> 2.4'
gem 'nokogiri', '~> 1.10'
gem 'rails-dom-testing', '~> 2.0'
gem 'crass', '~> 1.0'
gem 'loofah', '~> 2.3'
gem 'rails-html-sanitizer', '~> 1.2'
gem 'actionview', '~> 5.2'
gem 'rack', '~> 2.0'
gem 'rack-test', '~> 1.1'
gem 'actionpack', '~> 5.2'
gem 'nio4r', '~> 2.5'
gem 'websocket-extensions', '~> 0.1'
gem 'websocket-driver', '~> 0.7'
gem 'actioncable', '~> 5.2'
gem 'globalid', '~> 0.4'
gem 'activejob', '~> 5.2'
gem 'mini_mime', '~> 1.0'
gem 'mail', '~> 2.7'
gem 'actionmailer', '~> 5.2'
gem 'activemodel', '~> 5.2'
gem 'arel', '~> 9.0'
gem 'activerecord', '~> 5.2'
gem 'mimemagic', '~> 0.3.3'
gem 'marcel', '~> 0.3'
gem 'activestorage', '~> 5.2'
gem 'public_suffix', '~> 4.0'
gem 'addressable', '~> 2.7'
gem 'io-like', '~> 0.3'
gem 'archive-zip', '~> 0.12'
gem 'bindex', '~> 0.8'
gem 'msgpack', '~> 1.3'
gem 'bootsnap', '~> 1.4'
gem 'byebug', '~> 11.0'
gem 'regexp_parser', '~> 1.6'
gem 'xpath', '~> 3.2'
gem 'capybara', '~> 3.29'
gem 'childprocess', '~> 2.0'
gem 'chromedriver-helper', '~> 2.1'
gem 'coffee-script-source', '~> 1.12'
gem 'execjs', '~> 2.7'
gem 'coffee-script', '~> 2.4'
gem 'method_source', '~> 0.9'
gem 'thor', '~> 0.20'
gem 'railties', '~> 5.2'
gem 'connection_pool', '~> 2.2'
gem 'ffi', '~> 1.11'
gem 'rb-fsevent', '~> 0.10'
gem 'rb-inotify', '~> 0.10'
gem 'ruby_dep', '~> 1.5'
gem 'sidekiq', '~>6.0.0'
gem 'pg', '~>1.1.3'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
end

group :test do
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  gem 'chromedriver-helper'
end